### ISSUE TITLE
Issue in latest release

### ISSUE THREAD

**Issue by T3hBoy** [Kenan2000/BrightNights-Structured-Kenan-Modpack#120]
This one crashes the game
![01](https://user-images.githubusercontent.com/108841169/183146710-b7b59b71-4175-47a7-9437-ac4f88abf8df.png)
These ones not but it's weird they give errors now
![02](https://user-images.githubusercontent.com/108841169/183146714-d887d639-70a2-45ff-91c4-1ea99d3d34e6.png)
![03](https://user-images.githubusercontent.com/108841169/183146716-6b1554b9-073e-41fa-b0fd-07132c809c85.png)
![04](https://user-images.githubusercontent.com/108841169/183146720-27a6d07f-8114-4976-98bb-d2bd8fb57973.png)
![05](https://user-images.githubusercontent.com/108841169/183146722-d7d29cc2-ef11-42bf-81f5-adcac72def97.png)
![06](https://user-images.githubusercontent.com/108841169/183146725-e84b5372-415d-4503-a826-60bbfa99d6ad.png)
![07](https://user-images.githubusercontent.com/108841169/183146726-cd73bc5f-69ad-41ac-bdf5-e1c005e0776e.png)
![08](https://user-images.githubusercontent.com/108841169/183146729-cc993b14-c18c-419b-87f3-2db2f3da81e0.png)
![09](https://user-images.githubusercontent.com/108841169/183146730-82018e72-5154-46f5-9a84-7259b99c4b6c.png)
![10](https://user-images.githubusercontent.com/108841169/183146732-7a4339b6-f893-4062-9d1a-9b7dc601f644.png)
![11](https://user-images.githubusercontent.com/108841169/183146734-b0b2f052-93cd-4365-9e5a-23c4511dca82.png)
![12](https://user-images.githubusercontent.com/108841169/183146736-bcff420a-317b-4f82-be18-a2d57fb32d6d.png)
![13](https://user-images.githubusercontent.com/108841169/183146737-598b021e-de4f-4c16-8d07-dd41811a2b29.png)

**Comment by Kenan2000** [comment]
@T3hBoy I've fixed all of them, other errors that you have are actually from Chaosvolt's mods, they are not from mods in my Bright Nights Modpack hopefully as well

**Comment by T3hBoy** [comment]
![aaa](https://user-images.githubusercontent.com/108841169/183224995-b8f0de11-3ed6-4bc3-bf59-fc29d813e181.png)
Sorry but the error persists, not sure what's causing it
